import esbuild from "esbuild";
import fs from "fs";
import path from "path";
import process from "process";
import { fileURLToPath } from "url";
import builtins from "builtin-modules";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const prod = process.argv[2] === "production";

/**
 * `node esbuild.config.mjs production mini` builds MiniNUI: the same source
 * with the Bases views compiled out, written to main.mini.js beside main.js.
 * Only the release packaging reads that file; nothing else changes.
 */
const mini = process.argv.includes("mini");

/**
 * Production builds land next to the source, which is what the release workflow
 * uploads. Watch builds land in the development vault so Obsidian picks them up
 * on reload. Override the watch target with NUI_VAULT_PLUGIN_DIR.
 */
const DEV_VAULT_PLUGIN_DIR = path.resolve(
	__dirname,
	"../vault-example/.obsidian/plugins/nui",
);

const outDir = prod
	? __dirname
	: (process.env.NUI_VAULT_PLUGIN_DIR ?? DEV_VAULT_PLUGIN_DIR);

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, visit the plugin's GitHub repository.
*/
`;

/**
 * Mini builds resolve the Bases-view registration module to its no-op stub, so
 * the view code never enters the bundle. Nothing else differs.
 */
const miniStubPlugin = {
	name: "nui-mini-stub",
	setup(build) {
		build.onResolve({ filter: /register-bases-views$/ }, () => ({
			path: path.join(__dirname, "src/views/register-bases-views.mini.ts"),
		}));
	},
};

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: [path.join(__dirname, "src/main.ts")],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	define: { __NUI_MINI__: mini ? "true" : "false" },
	plugins: mini ? [miniStubPlugin] : [],
	outfile: path.join(outDir, mini ? "main.mini.js" : "main.js"),
});

/** Obsidian loads all three from the same folder; keep them in step. */
function copyStaticAssets() {
	if (outDir === __dirname) return;
	fs.mkdirSync(outDir, { recursive: true });
	for (const file of ["manifest.json", "styles.css"]) {
		fs.copyFileSync(path.join(__dirname, file), path.join(outDir, file));
	}
}

if (prod) {
	await context.rebuild();
	await context.dispose();
	process.exit(0);
} else {
	copyStaticAssets();
	fs.watch(__dirname, (_event, filename) => {
		if (filename === "manifest.json" || filename === "styles.css") {
			copyStaticAssets();
		}
	});
	console.log(`[${mini ? "mininui" : "nui"}] watching — output: ${outDir}`);
	await context.watch();
}
